# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-02 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=128)),
                ('year', models.CharField(max_length=128)),
                ('datetime', models.CharField(max_length=128)),
                ('weather', models.CharField(max_length=128)),
                ('t_low', models.CharField(max_length=128)),
                ('t_high', models.CharField(max_length=128)),
            ],
        ),
    ]
